#!/usr/bin/env bash
# Enable (or clear) local sister-crate path overrides for fleet development.
#
# Cargo.toml uses crates.io versions so GitHub CI works without sister checkouts.
# This script writes .cargo/config.toml with `paths = [...]` so local peft-rs /
# qlora-rs / vsa-optim-rs trees override the registry when present.
#
# Usage:
#   bash scripts/use-local-path-deps.sh           # enable overrides
#   bash scripts/use-local-path-deps.sh --clear   # remove overrides
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [[ "${1:-}" == "--clear" ]]; then
  if [[ -f .cargo/config.toml ]]; then
    rm -f .cargo/config.toml
    # remove empty .cargo dir if only config lived there
    rmdir .cargo 2>/dev/null || true
    echo "Cleared local path overrides (.cargo/config.toml removed)."
  else
    echo "No local path overrides to clear."
  fi
  exit 0
fi

mkdir -p .cargo

# Only include sister paths that actually exist so a partial fleet still works.
paths=()
for d in peft-rs qlora-rs vsa-optim-rs unsloth-rs; do
  if [[ -f "../${d}/Cargo.toml" ]]; then
    paths+=("\"../${d}\"")
  else
    echo "note: ../${d} not found — skip"
  fi
done

if [[ ${#paths[@]} -eq 0 ]]; then
  echo "error: no sister crates found next to axolotl-rs; nothing to enable" >&2
  exit 1
fi

{
  echo "# Generated by scripts/use-local-path-deps.sh — do not commit."
  echo "# Overrides crates.io peft-rs / qlora-rs / vsa-optim-rs with local SoTs."
  echo "paths = [$(IFS=', '; echo "${paths[*]}")]"
} > .cargo/config.toml

echo "Wrote .cargo/config.toml with paths:"
cat .cargo/config.toml
echo ""
echo "Run cargo update -p peft-rs -p qlora-rs -p vsa-optim-rs (as needed) after enabling."
